from Backend import db
from .User import User
from .Role import Role
from .Department import Department
from .UserDepartment import UserDepartment
from .CameraMonitoringLogs import CameraMonitoringLogs
from .DepartmentSection import DepartmentSection
from  .Camera import Camera
from  .Path import Path
from .UserBiometric import UserBiometric
from .Location import Location
from .EmployeeDesignation import EmployeeDesignation
from .AssignSupervisor import AssignSupervisor
from .AccessControl import AccessControl
from .Designation import Designation
from .CameraPath import CameraPath